server:
  port: 8083

spring:
  application:
    name: order-status-service
  h2:
    console:
      enabled: true
      path: /h2-console
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:h2:mem:orders_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate.jdbc.time_zone: UTC
        hibernate.format_sql: true
        hibernate.dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,camelroutes
  camelroutes:
    enabled: true

camel:
  component:
    kafka:
      brokers: localhost:9092
  main:
    run-controller: true
    log-startup-summary: true

app:
  topics:
    new: orders.new
    validated: orders.validated
    notified: orders.notified
    dlt: orders.status.dlt
