
server:
  port: 8083

spring:
  application:
    name: order-status-service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/orders
    username: orders
    password: orders
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

camel:
  springboot:
    name: order-status-service
  component:
    kafka:
      brokers: localhost:9092
      autoOffsetReset: earliest
      allowManualCommit: true

app:
  topics:
    new: orders.new
    validated: orders.validated
    notified: orders.notified
    dlt: orders.status.dlt