spring:
  application:
    name: inventory-service
  kafka:
    bootstrap-servers: localhost:9092

camel:
  component:
    kafka:
      brokers: localhost:9092
      group-id: inventory-service
      auto-offset-reset: earliest
      consumers-count: 1
      poll-timeout-ms: 3000
      seek-to: beginning
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      allow-manual-commit: false

  main:
    run-controller: true
    log-startup-summary: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,camelroutes
  camelroutes:
    enabled: true
server:
  port: 8081

#logging:
#  level:
#    org.apache.camel: DEBUG
#    org.apache.camel.kafka: DEBUG
#    org.apache.camel.processor: DEBUG