
version: "3.8"

services:
  postgres:
    container_name: order-platform-postgres
    image: postgres:16
    environment:
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders
      POSTGRES_DB: orders
    ports:
      - "5432:5432"

  pgadmin:
    container_name: order-platform-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: sthomas3@korewireless.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8089:80"
